"""item_values.source_input_id を ON DELETE CASCADE に

Revision ID: 577f4e4fc98b
Revises: 653e90ebac44
Create Date: 2026-09-12 22:40:01.666525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '577f4e4fc98b'
down_revision: Union[str, None] = '653e90ebac44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('item_values_source_input_id_fkey', 'item_values', type_='foreignkey')
    op.create_foreign_key(None, 'item_values', 'inquiry_inputs', ['source_input_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'item_values', type_='foreignkey')
    op.create_foreign_key('item_values_source_input_id_fkey', 'item_values', 'inquiry_inputs', ['source_input_id'], ['id'])
    # ### end Alembic commands ###
