"""initial 8 tables from 04-db

Revision ID: 653e90ebac44
Revises: 
Create Date: 2026-09-12 21:57:53.038085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '653e90ebac44'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('login_id', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), server_default='sales_clerk', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('sales_clerk')", name='ck_users_role'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_login_id'), 'users', ['login_id'], unique=True)
    op.create_table('inquiries',
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('status', sa.String(length=32), server_default='received', nullable=False),
    sa.Column('unreadable_reason', sa.String(length=32), nullable=True),
    sa.Column('submitted_by', sa.UUID(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('review_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_by', sa.UUID(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retention_until', sa.Date(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('received','reading','unreadable','awaiting_review','confirmed')", name='ck_inquiries_status'),
    sa.CheckConstraint("unreadable_reason IS NULL OR unreadable_reason IN ('illegible','no_items','timeout','max_turns')", name='ck_inquiries_unreadable_reason'),
    sa.ForeignKeyConstraint(['confirmed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_inquiries_retention_until', 'inquiries', ['retention_until'], unique=False)
    op.create_index('ix_inquiries_status_submitted_at', 'inquiries', ['status', sa.text('submitted_at DESC')], unique=False)
    op.create_table('agent_runs',
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('inquiry_id', sa.UUID(), nullable=False),
    sa.Column('attempt_no', sa.SmallInteger(), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('max_turns', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='running', nullable=False),
    sa.Column('stop_reason', sa.String(length=32), nullable=True),
    sa.Column('failure_reason', sa.String(length=32), nullable=True),
    sa.Column('turns', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trace_path', sa.String(length=1024), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("failure_reason IS NULL OR failure_reason IN ('illegible','no_items')", name='ck_agent_runs_failure_reason'),
    sa.CheckConstraint("status IN ('running','finished')", name='ck_agent_runs_status'),
    sa.CheckConstraint("stop_reason IS NULL OR stop_reason IN ('completed','failed','max_turns','inner_timeout','inactivity_timeout','outer_timeout')", name='ck_agent_runs_stop_reason'),
    sa.CheckConstraint('attempt_no IN (1, 2)', name='ck_agent_runs_attempt_no'),
    sa.ForeignKeyConstraint(['inquiry_id'], ['inquiries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('run_id'),
    sa.UniqueConstraint('inquiry_id', 'attempt_no', name='uq_agent_runs_inquiry_attempt')
    )
    op.create_index('ix_agent_runs_inquiry_started_at', 'agent_runs', ['inquiry_id', sa.text('started_at DESC')], unique=False)
    op.create_table('inquiry_inputs',
    sa.Column('inquiry_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('display_name', sa.String(length=512), nullable=False),
    sa.Column('format', sa.String(length=16), nullable=False),
    sa.Column('byte_size', sa.Integer(), nullable=True),
    sa.Column('storage_path', sa.String(length=1024), nullable=True),
    sa.Column('content_text', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), server_default='pending', nullable=False),
    sa.Column('unreadable_reason', sa.String(length=32), nullable=True),
    sa.Column('read_range', sa.String(length=512), nullable=True),
    sa.Column('row_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('excluded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('excluded_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(kind = 'file' AND storage_path IS NOT NULL AND content_text IS NULL) OR (kind = 'mail_body' AND content_text IS NOT NULL AND storage_path IS NULL)", name='ck_inputs_kind_payload'),
    sa.CheckConstraint("format IN ('excel','pdf','word','mail_body')", name='ck_inputs_format'),
    sa.CheckConstraint("kind IN ('file','mail_body')", name='ck_inputs_kind'),
    sa.CheckConstraint("status IN ('pending','read','read_no_items','unreadable')", name='ck_inputs_status'),
    sa.CheckConstraint("unreadable_reason IS NULL OR unreadable_reason = 'illegible'", name='ck_inputs_unreadable_reason'),
    sa.CheckConstraint('byte_size IS NULL OR byte_size <= 20971520', name='ck_inputs_size'),
    sa.ForeignKeyConstraint(['excluded_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['inquiry_id'], ['inquiries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_inquiry_inputs_inquiry_id', 'inquiry_inputs', ['inquiry_id'], unique=False)
    op.create_table('item_list_exports',
    sa.Column('inquiry_id', sa.UUID(), nullable=False),
    sa.Column('storage_path', sa.String(length=1024), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('pending_row_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['inquiry_id'], ['inquiries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inquiry_id')
    )
    op.create_table('item_rows',
    sa.Column('inquiry_id', sa.UUID(), nullable=False),
    sa.Column('row_no', sa.Integer(), nullable=False),
    sa.Column('classification', sa.String(length=32), nullable=False),
    sa.Column('source_opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('check_state', sa.String(length=16), server_default='unchecked', nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('checked_by', sa.UUID(), nullable=True),
    sa.Column('excluded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('excluded_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("check_state IN ('unchecked','checked')", name='ck_item_rows_check_state'),
    sa.CheckConstraint("classification IN ('needs_confirmation','low_confidence','high_confidence')", name='ck_item_rows_classification'),
    sa.ForeignKeyConstraint(['checked_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['excluded_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['inquiry_id'], ['inquiries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inquiry_id', 'row_no', name='uq_item_rows_inquiry_row_no')
    )
    op.create_index('ix_item_rows_inquiry_classification', 'item_rows', ['inquiry_id', 'classification'], unique=False)
    op.create_index('ix_item_rows_inquiry_row_no', 'item_rows', ['inquiry_id', 'row_no'], unique=False)
    op.create_table('item_values',
    sa.Column('item_row_id', sa.UUID(), nullable=False),
    sa.Column('field', sa.String(length=32), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('value_text', sa.Text(), nullable=True),
    sa.Column('quantity_value', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('due_kind', sa.String(length=32), nullable=True),
    sa.Column('due_start', sa.Date(), nullable=True),
    sa.Column('due_end', sa.Date(), nullable=True),
    sa.Column('confidence', sa.String(length=8), nullable=False),
    sa.Column('source_input_id', sa.UUID(), nullable=True),
    sa.Column('locator', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(state = 'extracted' AND raw_text IS NOT NULL AND source_input_id IS NOT NULL AND locator IS NOT NULL) OR (state = 'needs_confirmation' AND raw_text IS NULL AND source_input_id IS NULL AND locator IS NULL)", name='ck_item_values_extracted_needs_source'),
    sa.CheckConstraint("confidence IN ('high','low')", name='ck_item_values_confidence'),
    sa.CheckConstraint("due_kind IS NULL OR due_kind <> 'month_range' OR (due_start IS NOT NULL AND due_end IS NOT NULL AND due_start <= due_end AND date_trunc('month', due_start) = date_trunc('month', due_end))", name='ck_item_values_month_range'),
    sa.CheckConstraint("due_kind IS NULL OR due_kind IN ('fixed_date','month_range','needs_confirmation')", name='ck_item_values_due_kind'),
    sa.CheckConstraint("field IN ('item_name','model_no','quantity','unit','due_date','note')", name='ck_item_values_field'),
    sa.CheckConstraint("state IN ('extracted','needs_confirmation')", name='ck_item_values_state'),
    sa.ForeignKeyConstraint(['item_row_id'], ['item_rows.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_input_id'], ['inquiry_inputs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_row_id', 'field', name='uq_item_values_row_field')
    )
    op.create_index('ix_item_values_item_row_id', 'item_values', ['item_row_id'], unique=False)
    op.create_index('ix_item_values_source_input_id', 'item_values', ['source_input_id'], unique=False)
    op.create_table('value_clues',
    sa.Column('item_value_id', sa.UUID(), nullable=False),
    sa.Column('clue', sa.String(length=4), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("clue IN ('H1','H2','H3','H4')", name='ck_value_clues_clue'),
    sa.ForeignKeyConstraint(['item_value_id'], ['item_values.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_value_id', 'clue', name='uq_value_clues_value_clue')
    )
    op.create_index('ix_value_clues_item_value_id', 'value_clues', ['item_value_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_value_clues_item_value_id', table_name='value_clues')
    op.drop_table('value_clues')
    op.drop_index('ix_item_values_source_input_id', table_name='item_values')
    op.drop_index('ix_item_values_item_row_id', table_name='item_values')
    op.drop_table('item_values')
    op.drop_index('ix_item_rows_inquiry_row_no', table_name='item_rows')
    op.drop_index('ix_item_rows_inquiry_classification', table_name='item_rows')
    op.drop_table('item_rows')
    op.drop_table('item_list_exports')
    op.drop_index('ix_inquiry_inputs_inquiry_id', table_name='inquiry_inputs')
    op.drop_table('inquiry_inputs')
    op.drop_index('ix_agent_runs_inquiry_started_at', table_name='agent_runs')
    op.drop_table('agent_runs')
    op.drop_index('ix_inquiries_status_submitted_at', table_name='inquiries')
    op.drop_index('ix_inquiries_retention_until', table_name='inquiries')
    op.drop_table('inquiries')
    op.drop_index(op.f('ix_users_login_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
